### ISSUE TITLE
Could you please introduce how to build the problem file?

### ISSUE THREAD

**Issue by JackokieZhao** [LPMP/BDD#14]
If I have a million variables, can the solver work? Could you please explain how to build a problem file for the BDD?

In addition, the compile will break for the reason "/home/XXX/Downloads/BDD/include/run_solver_util.h(68): error: namespace "std" has no member "cout". If I add "# include <iostream>" in the header file, the compile will work.

**Comment by aabbas90** [comment]
Hi, 

1. If all variables are binary then yes.
2. Do you already have the problem description as an .LP format? Or not yet?
3. Thanks for reporting the error I guess you added #include <iostream> in the header?

**Comment by JackokieZhao** [comment]
Hi, 
2. I have only write my problem in pyomo/gurobi with python. And, I don't know how to export the problem to a ".LP" file.
3. Yeah, I have only add the "#include <iostream>".

**Comment by aabbas90** [comment]
You can export the .lp file from gurobi as:

`gurobi_model.write(exported.lp)`

Ref: https://www.gurobi.com/documentation/9.5/refman/py_model_write.html

**Comment by JackokieZhao** [comment]
This is the .lp file.

https://drive.google.com/file/d/1xmwVg0MQOzbLHZhKTwmVfMmqXdx_SR6k/view?usp=share_link

**Comment by aabbas90** [comment]
Thanks for providing the .lp file. The issue is we assume that each variable is present atleast once in a some constraint. For the provided file there are some which are not in any constraint. A simple way to fix this is by presolving first (which will remove such variables) and then do:

`model.presolve().write("test.lp")`

**Comment by JackokieZhao** [comment]
In addition, the work will be more popular if it has a python interface. I am thinking about how to call the BDD in my python source code.

**Comment by aabbas90** [comment]
1. Your given instance works if I remove the variable called `Constant` and also remove it from `Bounds` (line 5899). Basically we assume that the input instance does not contain already fixated values. 
2. Python interface is there but not complete. If you would like to use GPU solver then do `python setup.py install` in the root directory. An example to run is:

```
import BDD.ILP_instance_py as ilp_instance_bbd
import BDD.bdd_cuda_learned_mma_py as bdd_solver

bdd_ilp_instance = ilp_instance_bbd.read_ILP('YOUR_LP_FILE.LP')
solver = bdd_solver.bdd_cuda_learned_mma(bdd_ilp_instance, False, 1.0)

## DUAL SOLVER:
omega = 0.5 # parameter from FastDOG paper.
num_dual_iterations = 10000 # maximum allowed number of iterations, solver can terminate early due to convergence criteria below:
relative_improvement_slope = 1e-6 # good values are in [1e-6, 1e-9], smaller values will terminate early.
time_limit = 3600 # in seconds

solver.non_learned_iterations(omega, num_dual_iterations, relative_improvement_slope, time_limit)
solver.distribute_delta() # make deferred min-marginals zero.
lowerbound = solver.lower_bound()

## PRIMAL HEURISTIC:
init_delta = 1.1
delta_growth_rate = 1.1
num_dual_iterations_in_primal_rounding = 200
verbose = True
primal_solution = solver.primal_rounding_incremental(init_delta, delta_growth_rate, num_dual_iterations_in_primal_rounding, verbose)
```

**Comment by JackokieZhao** [comment]
The setup.py cannot be installed in my machine. The output log is as following:

`
(base) ➜  BDD git:(main) ✗ python ./setup.py install
running install
/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing src/BDD.egg-info/PKG-INFO
writing dependency_links to src/BDD.egg-info/dependency_links.txt
writing top-level names to src/BDD.egg-info/top_level.txt
file src/bdd_cuda_torch.py (for module bdd_cuda_torch) not found
reading manifest file 'src/BDD.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'src/BDD.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
file src/bdd_cuda_torch.py (for module bdd_cuda_torch) not found
file src/bdd_cuda_torch.py (for module bdd_cuda_torch) not found
running build_ext
Testing gcc...
...has version 9.5.0
Found suitable gcc/g++ version gcc g++
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/jackokie/Downloads/BDD/build/temp.linux-x86_64-cpython-39/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "/home/jackokie/Downloads/BDD/./setup.py", line 115, in <module>
    setup(
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/jackokie/Program/anaconda/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/jackokie/Downloads/BDD/./setup.py", line 33, in run
    self.build_extension(ext)
  File "/home/jackokie/Downloads/BDD/./setup.py", line 112, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/jackokie/Program/anaconda/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/jackokie/Downloads/BDD', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/jackokie/Downloads/BDD/build/lib.linux-x86_64-cpython-39/BDD', '-DPYTHON_EXECUTABLE=/home/jackokie/Program/anaconda/bin/python', '-DWITH_CUDA=ON', '-DCMAKE_GENERATOR=Ninja', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
`

**Comment by aabbas90** [comment]
Please try again with the latest code.

**Comment by JackokieZhao** [comment]
> Please try again with the latest code.

Great! It can be installed for python. Thanks for your work!
I have run the code https://github.com/LPMP/BDD/issues/14#issuecomment-1487071152.
But the simulation in python is about 111s, but it's 6s in the command line.  Why there's such a large range of different computer languages? And, the lower bound is also different between python and the command line.
Also, could you tell me how to get the results for the problem in the command line? What about python?

 I just wish the work was more perfect. There is no hostility. Thanks!

**Comment by aabbas90** [comment]
You are right. I will work on getting these things in order in coming days.

**Comment by JackokieZhao** [comment]
OK. Keep in touch. Looking forward to the improvement of the job.

**Comment by JackokieZhao** [comment]
Another test question:
The pyomo exported .lp file cannot be solved in the BDD library.
The following is pyomo exported file:
`\* Source Pyomo model name=hello *\

min 
x3:
+6 x1
+5 x2

s.t.

c_u_x4_:
+1 x1
+1 x2
<= 5

c_u_x5_:
+3 x1
+2 x2
<= 12

c_e_ONE_VAR_CONSTANT: 
ONE_VAR_CONSTANT = 1.0

bounds
   0 <= x1 <= +inf
   0 <= x2 <= +inf
end`

**Comment by aabbas90** [comment]
I have added python interface. Please check [py-interface](https://github.com/LPMP/BDD#python-interface)

**Comment by JackokieZhao** [comment]
Hi. The solver output a lower bound with many times iterations. But the lower bound is different with the Gurobi objective value.
For example, the objective value is 402800 in Gurobi, but its lower bound is 189199.9 in the BDD output. I don't konw whether the lower bound can be regarded as the objective value in BDD. And, I still cannot acquire the solved results for the variables.

**Comment by aabbas90** [comment]
1. Our lower bound should be matched with Gurobi's root relaxation objective. 
2. Do you mean [rounding](https://github.com/LPMP/BDD/blob/46a7746bb5d55bf7d471529c705c5beecafa4ec7/test/test_bdd_solver_py.py#L64) does not give a solution? If yes, then it is possible since it is just a heuristic (no guarantees).

**Comment by JackokieZhao** [comment]
I try to solve 0-1 linear programming problem. 
I don't know how to acquire the solved binary variables. Whether the final solution of original problem is "obj", and "sol" in the following code ? If this is the case, the BDD solution is different from the Gurobi.
In the Gurobi, the total number of 1 is 5 while it's 6 in the BDD solutions.
In addition, the objective value in Gurobi is 39600 while it's 475200 in the BDD.
So, I really don't know how to get the right solutions in the BDD.

The problem is attached in the following link.
https://drive.google.com/file/d/1xmwVg0MQOzbLHZhKTwmVfMmqXdx_SR6k/view?usp=sharing

`# Initialize solver:
solver = bdd_solver(opts)

# Solve dual problem:
solver.solve_dual()
assert solver.lower_bound() + 1e-5 >= -6.0

# Run primal heuristic:
obj, sol = solver.round()
assert obj == -6.0`

**Comment by aabbas90** [comment]
1. Our solver is competitive only on very large problems. If your instances are already solved by Gurobi in a reasonable time then there is not much benefit of using our solver. Also for small instances you should use `fastdog_cpu`. 
2. `obj` is the objective values of primal solution and `sol` is the variable assignment.
3. You can remove the assertions in your code, they were only part of test for that specific instance. 
4. As stated earlier: our solver comes with no guarantees. So the solution can be worse than Gurobi.
