### ISSUE TITLE
Python bindings no targets

### ISSUE THREAD

**Issue by paul0noah** [LPMP/BDD#16]
After commit `99d13dfe34ed0d5c4ecbd69cdf39d4d690117903` i get the following error when installing the python bindings
```bash
make: *** No rule to make target bdd_mp_py.  Stop.
Traceback (most recent call last):
  File "setup.py", line 148,
```
When i revert back to commit "[Added pybind11 json conversion.](https://github.com/LPMP/BDD/commit/361ffe9ede5e9d13561cfa31801421708e153591)"
everything works just fine.

So i guess the newest commit destroys the python binding setup through cmake

**Comment by paul0noah** [comment]
Follow up: 
when using the above linked commit the installation runs fine. But when i run in python the following
```
import BDD.bdd_solver
```
i get the error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'BDD.bdd_solver'
```

When i use commit f377a82736435bc4988e2c41e5c8029c168e9505
everything works. So somwhere after this commit the python bindings break.
